### ISSUE TITLE
Custom App Bar Button loses Interaction Receiver on build

### ISSUE THREAD

**Issue by ahohls** [Microsoft/MixedRealityDesignLabs_Unity#45]
Hi,
I`ve run into this problem trying to add a custom button to the app bar prefab. For testing purposes the custom button changes the color of a cube with an attached Color Receiver. 
I select the app bar prefab in the assets folder, add the text for the button and select the cube as the interaction receiver. (Is this even the right way to customize the app bar prefab?)
Hitting play in Unity everything works as it should but as soon as i build the project to use with the HoloLens emulator the interaction receiver of the custom button is reset to "none". The custom button itself remains in the app bar with the assigned label text but loses its functionality.
I would gladly appreciate any help to solve this.

**Comment by Railboy** [comment]
If you're setting the interaction receiver to an object in the scene, that reference will only last as long as the scene is open.

If you drag the app bar into your scene the reference to your InteractionReceiver will be preserved. However this instance of the prefab will not be the one referenced in the Interaction Manager, so you'll need to write a custom targeting script to summon it, instead of using BoundingBoxTarget.

There's been a fair amount of confusion over how to use the custom button functionality. We're going to redesign the custom button workflow and interface to make using it more straightforward. Feel free to describe your ideal use case.

**Comment by ahohls** [comment]
Thanks for clearing that up, makes perfect sense now. 
I think what's slightly confusing is that a custom button retains its name but not the interaction receiver. But which is only logical as the name is only bound to the button and not to any objects in the scene.

My use case was to expand the functionality of the app bar to add new ways to manipulate holograms. I was planning to use custom buttons with new/modified receiver scripts that I would create and attach to the buttons. This way I wanted to be able to change the color of a hologram and to instantiate a duplicate of a hologram. Other functions might be neede further along in my project, these are not entirely clear as of this point.

Thanks for your help!

**Comment by ChrisSzkoda** [comment]
Can you please and update/fix this error #
