### ISSUE TITLE
SharedHolograms from the HTK stop working as soon as MRDL is imported

### ISSUE THREAD

**Issue by ToWalter** [Microsoft/MixedRealityDesignLabs_Unity#75]
I worked with the example project for shared Holograms for testing purposes. Then I merged my existing project (which included MRDL) into the SharedHolograms stuff and I couldn't connect the client to the server anymore. I can't see an error in the application, since the client is just not showing up the shared Holograms. Then I started debugging and it seems, that the InteractionManager from MRDL is interfering with the shared Holograms stuff.

**Comment by paseb** [comment]
Please grab this PR from the MRTK:
- https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1197

We're merging the base functionality from MRDL to MRTK so they place nice :).

**Comment by HattMarris1** [comment]
Is the only way to use the boundingbox/appbar at the moment is to use and older version of the MRTK?

**Comment by hooplapunta** [comment]
Just to clarify, if I currently wanted to use both MRTK and MRDL in the same project with Sharing for HoloLens over the classic Holotoolkit sharing system (not UNet), which combination of versions/PRs of the following should I use?
- Unity
- MRTK/HoloTookit
- MRDL

Thanks so much! You guys are doing an amazing job and love the bounding box... which is why I want to use MRDL!
